name: create-app-token
on: [workflow_dispatch]

jobs:
  hello-world:
    runs-on: Ubuntu22.04
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: actions-int
        env:
          GITHUB_API_URL: "https://${{ secrets.SERVER_URL }}/api/v3/"
      - name: print token
        run: echo ${{ steps.app-token.outputs.token }}
      - name: Checkout private repository      
        uses: actions/checkout@v4  
        with:    
          repository: actions-int/composite-workflows
          ref: main
          token: ${{ steps.app-token.outputs.token }}
          path: composite-workflows
