name: test-authorize-collab

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronized

jobs:
  authorize:
    runs-on: Ubuntu22.04

    steps:
      - name: Retrieve the collaborator
        run: echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
      - name: Authorize the PR Author
        uses: actions/github-script@v6
        with:
          script: |
            const collab_author = process.env.PR_AUTHOR;
            const isCollaborator = await github.orgs.checkMembership({
              org: 'Xilinx',
              username: collab_author
            });

            if (isCollaborator.data) {
              console.log('Author ${collab_author} is a trusted outside collaborator');
            } else {
              console.log('Author ${collab_author} is not a trusted outside collaborator');
              process.exit(1);
            }
