name: test-authorize-collab

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronized

jobs:
  authorize:
    runs-on: Ubuntu22.04

    steps:
      - name: Retrieve the collaborator
        run: echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
        
      - name: Authorize the PR Author
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CI_ACCESS_TOKEN }}
          script: |
            const collab_author = process.env.PR_AUTHOR;
            const isCollaborator = await github.rest.repos.checkCollaborator({
              owner: 'Xilinx',
              repo: 'xrt',
              username: collab_author
            });

            if (isCollaborator.data) {
              console.log("Author is a trusted outside collaborator: " + collab_author);
            } else {
              console.log("Author is not a trusted outside collaborator: "+ collab_author);
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: "Author is not a collaborator: " + collab_author + "\n can we please validate PR"
              });
              process.exit(1);
            }
