name: xrt-authorize-ci

on:
  pull_request_target:
     types:
      - opened
      - edited
      - synchronized
 
env:  
  RELEASE: '2024.1'
  PIPELINE: 'xrt' 
  ENV: 'test' 
  
jobs:

  authorize:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve the collaborator
        run: echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
        
      - name: Authorize the PR Author
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CI_ACCESS_TOKEN }}
          script: |
            const collab_author = process.env.PR_AUTHOR;
            const isCollaborator = await github.rest.repos.checkCollaborator({
              owner: 'Xilinx',
              repo: 'preflight-check',
              username: collab_author, 
            });

            const collaboratorPermission = await github.rest.repos.getCollaboratorPermissionLevel({
              owner: 'Xilinx',
              repo: 'preflight-check',
              username: collab_author, 
            });
            console.log(collaboratorPermission)
            console.log(collaboratorPermission.data.user.permissions.push)
            
            if (isCollaborator.status == "204" && collaboratorPermission.data.user.permissions.push) {
              console.log("Author is a trusted outside collaborator: " + collab_author);
            } else {
              console.log("Author is not a trusted outside collaborator: "+ collab_author);
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: collab_author + " - is not a collaborator " + "\n Can XRT admins please validate PR"
              });
              process.exit(1);
            }
  
  build:
    needs: authorize
    strategy:      
      matrix:      
        include:      
          - os: centos78      
            packageType: rpm      
          - os: centos8      
            packageType: rpm      
          - os: rhel9      
            packageType: rpm      
          - os: ubuntu2004      
            packageType: deb      
          # - os: ubuntu2204      
          #   packageType: deb      
        
    runs-on: [self-hosted, Ubuntu-22.04]
    steps:  
      - name: Set env variables    
        run: |    
          echo "Setting environment variables..."      
          echo "XRT_VERSION_PATCH=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV    
          echo "PATH=/usr/bin:$PATH" >> $GITHUB_ENV
          
      - name: Checkout PR   
        uses: actions/checkout@v4 
        with: 
          repository: "${{ github.event.pull_request.head.repo.full_name }}"
          ref: "${{ github.event.pull_request.head.ref }}"
          fetch-depth: 0
          github-server-url: "https://github.com" 
          token: ${{ secrets.CI_CLOUD_TOKEN}}
          path: ${{ github.workspace }}/${{ github.run_number }}  
          submodules: recursive  
   
      - name: Test authorization   
        run: echo "Running Build pipeline"
    
